/**
 * build-config.js
 * Runs during Netlify/Vercel build to generate assets/js/config.js
 * from environment variables — so real keys are NEVER in the repo.
 */
const fs = require('fs');

const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_ANON_KEY || '';

if (!url || !key) {
    console.warn('⚠️  WARNING: SUPABASE_URL or SUPABASE_ANON_KEY env var is missing!');
}

const content = `// Auto-generated by build-config.js — DO NOT EDIT MANUALLY
window.CARVOYAGE_CONFIG = {
    SUPABASE_URL:      '${url}',
    SUPABASE_ANON_KEY: '${key}'
};
`;

fs.writeFileSync('assets/js/config.js', content, 'utf8');
console.log('✅ config.js generated successfully.');
